### PR TITLE
Adding a .gitattributes to enforce LF eol's

### PR DESCRIPTION
**Pull request by AndyM84**
Just adding this so the next time I push something here it smacks me if I forget to switch line endings.

### CODE REVIEW

**Comment by AndyM84** [comment]
Also added something to demo maybe a nicer way of handling parameters on the query types.  We could easily apply this to everything, and it would make things start looking like this for usage:

``` php
    $alerts = new Queries\alerts;

    try {
        $result = $alerts->excludeServiceAlerts()->getAlerts();
    } catch (AlertNotAvailable $e) {
        echo $e->errorMessage();
        exit;
    }
```

**Comment by standaloneSA** [comment]
Nice. I wasn't aware of the .gitattributes feature. Thanks for adding that. 

Would it be better to throw an exception, rather than print an error message?

**Comment by AndyM84** [comment]
Sorry, the question about exceptions, is that geared toward the second commit with the getters/setters?  If so, that's just code I took from the libMBTA.php file.  If you're referring to the .gitattributes stuff this is a git process, so that when a commit is done it yells instead of just letting the commit go through.  So exceptions aren't really relevant at that point.

**Comment by standaloneSA** [comment]
Sorry for the delay on my part. I finally got to look into it more deeply. I dig. Adding it now. Thanks!

**Comment by AndyM84** [comment]
No worries whatsoever!  Let me know if you want me to go through and change the other classes to be similar (with the getter/setter sort of things).

Andy

Sent from Surface

From: Matt Simmons
Sent: ‎Saturday‎, ‎March‎ ‎28‎, ‎2015 ‎4‎:‎45‎ ‎AM
To: standaloneSA/libMBTA
Cc: Andrew Male

Sorry for the delay on my part. I finally got to look into it more deeply. I dig. Adding it now. Thanks!

**Pull request merged**
